RestService/Controllers/AlarmTrendController.cs
using AgileMQ.Interfaces;
using Microsoft.AspNetCore.Mvc;
using RestService.Directories.PervasiveBuilding.Alarm.Enum;
using RestService.Models;
using PervasiveRoomModels = RestService.Directories.PervasiveBuilding.Room.Models;
using PervasiveAlarmModels = RestService.Directories.PervasiveBuilding.Alarm.Models;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RestService.Controllers
{
   public class AlarmTrendController : Controller
   {
      private IAgileBus bus;

      public AlarmTrendController(IAgileBus bus)
      {
         this.bus = bus;
      }

      public IActionResult Index()
      {
         return View();
      }

      public IActionResult About()
      {
         ViewData["Message"] = "Your application description page.";

         return View();
      }

      public IActionResult Contact()
      {
         ViewData["Message"] = "Your contact page.";

         return View();
      }

      public IActionResult Error()
      {
         return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
      }

      public async Task<ActionResult> AlarmTrendAsync()
      {
         //Get all rooms
         Dictionary<string, object> roomFilter = new Dictionary<string, object>
         {
            { "floorNumber", null },
            { "roomNumber", null },
         };
         List<PervasiveRoomModels.Room> roomList = await bus.GetListAsync<PervasiveRoomModels.Room>(roomFilter);

         //Get all alarms
         Dictionary<string, object> alarmFilter = new Dictionary<string, object>
         {
            { "alarmType", null },
            { "roomId", null },
         };
         List<PervasiveAlarmModels.Alarm> alarmList = await bus.GetListAsync<PervasiveAlarmModels.Alarm>(alarmFilter);

         var model = GetDataAssets(GetAlarmTrendModel(alarmList, roomList));

         return View(model);
      }

      private string[][] GetDataAssets(AlarmTrendModel Model)
      {
         List<string[]> data = new List<string[]>();

         foreach (var kvpair in Model.Fire)
         {
            data.Add(new[] { kvpair.Key.ToString(), Model.Intrusion[kvpair.Key].ToString(), kvpair.Value.ToString() });
         }

         return data.ToArray();
      }

      private AlarmTrendModel GetAlarmTrendModel(List<PervasiveAlarmModels.Alarm> AlarmList, List<PervasiveRoomModels.Room> RoomList)
      {
         //Building models adding room and then countign events on it
         var intrusionModel = new Dictionary<long, int>();
         var fireModel = new Dictionary<long, int>();

         foreach (PervasiveRoomModels.Room room in RoomList)
         {
            intrusionModel.Add(room.Id.Value, 0);
            fireModel.Add(room.Id.Value, 0);

            //Count events on this room
            foreach (PervasiveAlarmModels.Alarm alarm in AlarmList.Where(a => a.RoomId == room.Id.Value).ToList())
            {
               switch (alarm.Type)
               {
                  case AlarmType.Fire:
                     //Update value
                     fireModel[room.Id.Value] = fireModel[room.Id.Value] + 1;
                     break;

                  case AlarmType.Intrusion:
                     //Update value
                     intrusionModel[room.Id.Value] = intrusionModel[room.Id.Value] + 1;
                     break;
               }
            }
         }

         return new AlarmTrendModel()
         {
            Fire = fireModel,
            Intrusion = intrusionModel,
         };
      }
   }
}

RestService/Controllers/RoomTrendController.cs
using AgileMQ.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using RestService.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using PervasiveRoomModels = RestService.Directories.PervasiveBuilding.Room.Models;
using PervasiveTemperatureModels = RestService.Directories.PervasiveBuilding.Temperature.Models;

namespace RestService.Controllers
{
   public class RoomTrendController : Controller
   {
      private IAgileBus bus;

      public RoomTrendController(IAgileBus bus)
      {
         this.bus = bus;
      }

      public IActionResult Index()
      {
         return View();
      }

      public IActionResult About()
      {
         ViewData["Message"] = "Your application description page.";

         return View();
      }

      public IActionResult Contact()
      {
         ViewData["Message"] = "Your contact page.";

         return View();
      }

      public IActionResult Error()
      {
         return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
      }

      public ActionResult RoomSelector()
      {
         if (TempData["ERROR"] != null)
         {
            ModelState.AddModelError("ERROR", TempData["ERROR"].ToString());
         }

         if (!ModelState.IsValid)
         {
            return View(ModelState);
         }
         else
         {
            return View();
         }
      }

      public async Task<ActionResult> RoomTrendAsync(RoomTrendModel Model)
      {
         //Checking if the user insert all fields
         if (Model.Date == null)
         {
            TempData["ERROR"] = "Please Select a Date";
            return RedirectToAction("RoomSelector", "RoomTrend");
         }

         if (Model.RoomNumber == null)
         {
            TempData["ERROR"] = "Please Select a Room Number";
            return RedirectToAction("RoomSelector", "RoomTrend");
         }

         if (Model.FloorNumber == null)
         {
            TempData["ERROR"] = "Please Select a Floor Number";
            return RedirectToAction("RoomSelector", "RoomTrend");
         }

         //Getting the selected room
         Dictionary<string, object> roomFilter = new Dictionary<string, object>
         {
            { "floorNumber", Model.FloorNumber },
            { "roomNumber", Model.RoomNumber },
         };
         List<PervasiveRoomModels.Room> RoomList = await bus.GetListAsync<PervasiveRoomModels.Room>(roomFilter);

         //Check if the room exist or not
         if (RoomList.Count == 0)
         {
            TempData["ERROR"] = "Non-Existent Room";
            return RedirectToAction("RoomSelector", "RoomTrend");
         }

         //Get all temperature of this room
         Dictionary<string, object> temperatureFilter = new Dictionary<string, object>
         {
            { "roomId", RoomList[0].Id },
         };
         List<PervasiveTemperatureModels.Temperature> temperatureList = await bus.GetListAsync<PervasiveTemperatureModels.Temperature>(temperatureFilter);

         //Filtering temperature getting all temperature of the selected month
         var returnModel = temperatureList.
            Where(tmp => tmp.InsertionDate.Value.Month == Model.Date.Value.Month && tmp.InsertionDate.Value.Year == Model.Date.Value.Year)
            .ToList();

         return View(returnModel);
      }
   }
}

RestService/Controllers/TemperatureVariationController.cs
using AgileMQ.Interfaces;
using Microsoft.AspNetCore.Mvc;
using RestService.Models;
using PervasiveRoomModels = RestService.Directories.PervasiveBuilding.Room.Models;
using PervasiveTemperatureModels = RestService.Directories.PervasiveBuilding.Temperature.Models;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System;

namespace RestService.Controllers
{
   public class TemperatureVariationController : Controller
   {
      private IAgileBus bus;

      public TemperatureVariationController(IAgileBus bus)
      {
         this.bus = bus;
      }

      public IActionResult Index()
      {
         return View();
      }

      public IActionResult About()
      {
         ViewData["Message"] = "Your application description page.";

         return View();
      }

      public IActionResult Contact()
      {
         ViewData["Message"] = "Your contact page.";

         return View();
      }

      public IActionResult Error()
      {
         return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
      }

      public async Task<ActionResult> TemperatureVariationAsync()
      {
         //Get all rooms
         Dictionary<string, object> roomFilter = new Dictionary<string, object>
         {
            { "floorNumber", null },
            { "roomNumber", null },
         };
         List<PervasiveRoomModels.Room> roomList = await bus.GetListAsync<PervasiveRoomModels.Room>(roomFilter);

         //Get All Temperatures
         Dictionary<string, object> filter = new Dictionary<string, object>
         {
            { "roomId", null },
         };
         List<PervasiveTemperatureModels.Temperature> temperatureList = await bus.GetListAsync<PervasiveTemperatureModels.Temperature>(filter);

         var model = GetDataAssets(GetTemperatureVariationModel(temperatureList, roomList));

         return View(model);
      }

      private string[][] GetDataAssets(TemperatureVariationModel Model)
      {
         List<string[]> data = new List<string[]>();

         foreach (var kvpair in Model.Max)
         {
            data.Add(new[] { kvpair.Key.ToString(), Convert.ToDouble(Model.Min[kvpair.Key]).ToString(System.Globalization.CultureInfo.InvariantCulture), Convert.ToDouble(kvpair.Value).ToString(System.Globalization.CultureInfo.InvariantCulture) });
         }

         return data.ToArray();
      }

      private TemperatureVariationModel GetTemperatureVariationModel(List<PervasiveTemperatureModels.Temperature> TemperatureList, List<PervasiveRoomModels.Room> RoomList)
      {
         //Building models adding room and then countign events on it
         var maxModel = new Dictionary<long, double>();
         var minModel = new Dictionary<long, double>();

         foreach (PervasiveRoomModels.Room room in RoomList)
         {
            //Add MIN
            var minTempList = TemperatureList.Where(
               tmp => tmp.RoomId == room.Id.Value
               && tmp.InsertionDate.Value.Hour == 7 && tmp.InsertionDate.Value.Minute == 0).ToList();

            minModel.Add(room.Id.Value, minTempList.Sum(t => t.TemperatureValue.Value) / minTempList.Count);

            //Add MAX
            var maxTempList = TemperatureList.Where(
               tmp => tmp.RoomId == room.Id.Value
               && tmp.InsertionDate.Value.Hour == 19 && tmp.InsertionDate.Value.Minute == 0).ToList();

            maxModel.Add(room.Id.Value, maxTempList.Sum(t => t.TemperatureValue.Value) / maxTempList.Count);
         }

         return new TemperatureVariationModel()
         {
            Max = maxModel,
            Min = minModel,
         };
      }
   }
}

RestService/Views/RoomTrend/RoomSelector.cshtml
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            background-color: aquamarine;
        }

        .ui-datepicker-calendar {
            display: none;
        }

        * {
            box-sizing: border-box;
        }

        a {
            width: 100%;
            height: 100%;
            text-decoration: none;
            color: cornflowerblue;
        }

        .menu {
            float: left;
            width: 20%;
            text-align: center;
        }

        .menuitem {
            background-color: mediumaquamarine;
            padding: 10px;
            min-width: 290px;
            margin-top: 7px;
            color: white;
        }

        .main {
            float: left;
            width: 60%;
            min-width: 350px;
            padding: 0 20px;
        }

        .right {
            background-color: mediumaquamarine;
            float: left;
            width: 20%;
            min-width: 290px;
            padding: 15px;
            margin-top: 7px;
            text-align: center;
        }
    </style>

    <script type="text/javascript">
        $(function () {
            $('.date-picker').datepicker(
                {
                    dateFormat: "mm/yy",
                    changeMonth: true,
                    changeYear: true,
                    showButtonPanel: true,
                    onClose: function (dateText, inst) {

                        function isDonePressed() {
                            return ($('#ui-datepicker-div').html().indexOf('ui-datepicker-close ui-state-default ui-priority-primary ui-corner-all ui-state-hover') > -1);
                        }

                        if (isDonePressed()) {
                            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                            $(this).datepicker('setDate', new Date(year, month, 1)).trigger('change');

                            $('.date-picker').focusout()//Added to remove focus from datepicker input box on selecting date
                        }
                    },
                    beforeShow: function (input, inst) {

                        inst.dpDiv.addClass('month_year_datepicker')

                        if ((datestr = $(this).val()).length > 0) {
                            year = datestr.substring(datestr.length - 4, datestr.length);
                            month = datestr.substring(0, 2);
                            $(this).datepicker('option', 'defaultDate', new Date(year, month - 1, 1));
                            $(this).datepicker('setDate', new Date(year, month - 1, 1));
                            $(".ui-datepicker-calendar").hide();
                        }
                    }
                })
        });
    </script>

</head>

<body style="font-family:Verdana;color:#aaaaaa;">

    

    <div style="background-color:mediumaquamarine;padding:15px;text-align:center;">
        <h1 style="color:white">Smart Building</h1>
    </div>

    <div style="overflow:auto">
        <div class="menu">
            <div class="menuitem"> <a href="@Url.Action("Index", "Home")">Home</a> </div>
            <div class="menuitem"> <a href="@Url.Action("AlarmTrendAsync", "AlarmTrend")">Alarms Trends</a> </div>
            <div class="menuitem"> <a href="@Url.Action("TemperatureVariationAsync", "TemperatureVariation")">Temperature Variation</a></div>
        </div>

        <div class="main">
            <h2 style="color:white">Specify which room you would like to analyze</h2>

            @using (Html.BeginForm("RoomTrendAsync", "RoomTrend", FormMethod.Post))
            {
                <input asp-for="RoomNumber" name="RoomNumber" type="number" id="RoomNumber" placeholder="Room Number" />
                <input asp-for="FloorNumber" name="FloorNumber" type="number" id="FloorNumber" placeholder="Floor Number" />
                <input asp-for="Date" name="Date" id="Date" class="date-picker" />
                <input class="button" id="submit" type="submit" value="Search" />
             } 
            <p style="color:red">@Html.ValidationMessage("ERROR")</p>          
        </div>
    </div>

    <div style="background-color:mediumaquamarine;text-align:center;padding:10px;margin-top:7px; color:white">© Copyright Andrea Nicolini - University of Bologna</div>

</body>
</html>

RestService/Views/RoomTrend/RoomTrendAsync.cshtml
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            background-color: aquamarine;
        }

        .ui-datepicker-calendar {
            display: none;
        }

        * {
            box-sizing: border-box;
        }

        a {
            width: 100%;
            height: 100%;
            text-decoration: none;
            color: cornflowerblue;
        }

        .menu {
            float: left;
            width: 20%;
            text-align: center;
        }

        .menuitem {
            background-color: mediumaquamarine;
            padding: 10px;
            min-width: 290px;
            margin-top: 7px;
            color: white;
        }

        .main {
            float: left;
            width: 60%;
            min-width: 350px;
            padding: 0 20px;
        }

        .right {
            background-color: mediumaquamarine;
            float: left;
            width: 20%;
            min-width: 290px;
            padding: 15px;
            margin-top: 7px;
            text-align: center;
        }
    </style>

    <script type="text/javascript">

        function DrawCharts() {

            var data_humidity = new google.visualization.DataTable();
            data_humidity.addColumn('number', 'X');
            data_humidity.addColumn('number', '%');

            var data_temperature = new google.visualization.DataTable();
            data_temperature.addColumn('number', 'X');
            data_temperature.addColumn('number', '°C');

            var options_humidity = {
                title: 'Humidity Trend',
                hAxis: {},
                vAxis: { title: 'Humidity' }
            };

            var options_temperature = {
                title: 'Temperature Trend',
                hAxis: {},
                vAxis: { title: 'Temperature' }
            };

            var model = convertModel();

            for (var n = 0; n < model.length; n++) {
                data_humidity.addRows([
                    [n, model[n].Humidity],
                ]);

                data_temperature.addRows([
                    [n, model[n].Temperature],
                ]);
            }

            var chart_humidity = new google.visualization.LineChart(document.getElementById('chart_div_humidity'));
            chart_humidity.draw(data_humidity, options_humidity);

            var chart_temperature = new google.visualization.LineChart(document.getElementById('chart_div_temperature'));
            chart_temperature.draw(data_temperature, options_temperature);
        }

        function convertModel() {
            var model = [];
            @foreach (var item in Model)
            {
                @:model.push({
                @:Temperature: @item.TemperatureValue,
                @:Humidity: @item.HumidityValue,
                @:});
            }
            console.log(model);
            return model;
        }
    </script>

</head>

<body style="font-family:Verdana;color:#aaaaaa;" onload="DrawCharts()">

    <div style="background-color:mediumaquamarine;padding:15px;text-align:center;">
        <h1 style="color:white">Smart Building</h1>
    </div>

    <div style="overflow:auto">
        <div class="menu">
            <div class="menuitem"> <a href="@Url.Action("Index", "Home")">Home</a> </div>
            <div class="menuitem"> <a href="@Url.Action("AlarmTrendAsync", "AlarmTrend")">Alarms Trends</a> </div>
            <div class="menuitem"> <a href="@Url.Action("TemperatureVariationAsync", "TemperatureVariation")">Temperature Variation</a></div>
        </div>

        <div class="main">
            <h2 style="color:white">Temperature & Humidity Trends</h2>
            <div style="padding:20px;width:100%; height:100%" id="chart_div_temperature"></div>
            <div style="padding:20px; width:100%; height:100%" id="chart_div_humidity"></div>
        </div>
    </div>

    <div style="background-color:mediumaquamarine;text-align:center;padding:10px;margin-top:7px; color:white">© Copyright Andrea Nicolini - University of Bologna</div>

</body>
</html>